/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "stm32l4xx.h"
#include "stm32l4xx_gpio_driver.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

// Simple delay function
void delay()
{
	for(uint32_t i = 0; i < 500000; i++);  // Short pause
}

int main(void)
{
    /* LED setup */
	GPIO_Handle_t GpioLed;

	GpioLed.pGPIOx = GPIOA;                        // Use port A
	GpioLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_5; // Pin 5
	GpioLed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;   // Output mode
	GpioLed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST; // Fast speed
	GpioLed.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP; // Push-pull
	GpioLed.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD; // No pull-up/pull-down

	GPIO_PeriClockControl(GPIOA, ENABLE); // Turn on clock for GPIOA
	GPIO_Init(&GpioLed);                  // Apply settings to pin

	while(1)  // Loop forever
	{
		GPIO_ToggleOutputPin(GPIOA, GPIO_PIN_NO_5); // Toggle LED
		delay();                                    // Wait a bit
	}
}
